application:
  name: Training Platform
  port: 5888
  timeout: 500

log:
  log_level: debug
  folder: ./log/
  file: messages.log

DB:
  ip: 127.0.0.1
  port: 3306
  user: root
  password: 12345678
  database: stp
  max_conn: 10
  max_idle: 10
  idle_time: 3600
  print_sql: true

user:
  default_username: DefaultUser
  fetch_size: 10
